In [2]:
import numpy as np

In [ ]:
# 0차원 텐서 : Zeroth-order tensor
t0 = np.array(5.)
print("Value of t0 : ", t0)
print("Rank of t0 : ", t0.ndim)
print("Shape of t0 : ", t0.shape)
print("Size of t0 : ", t0.size)


Value of t0 :  5.0
Rank of t0 :  0
Shape of t0 :  ()
Size of t0 :  1


In [ ]:
# 1차원 텐서 : First-order tensor
t1 = np.array([0., 1., 2., 3., 4., 5.])
print("Value of t1 : ", t1)
print("Rank of t1 : ", t1.ndim)
print("Shape of t1 : ", t1.shape)
print("Size of t1 : ", t1.size)


Value of t0 :  [0. 1. 2. 3. 4. 5.]
Rank of t0 :  1
Shape of t0 :  (6,)
Size of t0 :  6


In [ ]:
# 2차원 텐서 : Second-order tensor
t2 = np.array([ [0., 1.], [2., 3.], [4., 5.] ])
print("Value of t2 : ", t2)
print("Rank of t2 : ", t2.ndim)
print("Shape of t2 : ", t2.shape)
print("Size of t2 : ", t2.size)


Value of t2 :  [[0. 1.]
 [2. 3.]
 [4. 5.]]
Rank of t2 :  2
Shape of t2 :  (3, 2)
Size of t2 :  6


In [ ]:
# 3차원 텐서 : Third-order tensor
t3 = np.array([ [ [0., 1.], [2., 3.], [4., 5.] ], [ [6., 7.], [8., 9.], [10., 11.] ] ])
print("Value of t3 : ", t3)
print("Rank of t3 : ", t3.ndim)
print("Shape of t3 : ", t3.shape)
print("Size of t3 : ", t3.size)


Value of t3 :  [[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]]
Rank of t3 :  3
Shape of t3 :  (2, 3, 2)
Size of t3 :  12


In [ ]:
# 4차원 텐서 : Fourth-order tensor
t4 = np.array([ [ [0., 1.], [2., 3.], [4., 5.] ], [ [6., 7.], [8., 9.], [10., 11.] ], [ [12., 13.], [14., 15.], [16., 17.] ], [ [18., 19.], [20., 21.], [22., 23.] ], [ [24., 25.], [26., 27.], [28., 29.] ], [ [30., 31.], [32., 33.], [34., 35.] ] ])
print("Value of t4 : ", t4)
print("Rank of t4 : ", t4.ndim)
print("Shape of t4 : ", t4.shape)
print("Size of t4 : ", t4.size)


Value of t4 :  [[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]

 [[24. 25.]
  [26. 27.]
  [28. 29.]]

 [[30. 31.]
  [32. 33.]
  [34. 35.]]]
Rank of t4 :  3
Shape of t4 :  (6, 3, 2)
Size of t4 :  36


In [4]:
m1 = np.array([[1,4,5], [5,6,7]])
m2 = np.array([[6,0], [-1,10], [3, -5]])

np.matmul(m1,m2)

array([[17, 15],
       [45, 25]])

In [5]:
m1 = np.array([[1.,4.,5.], [5.,6.,7.]])
m2 = np.array([[6.,0.], [-1.,10.], [3., -5.]])

np.matmul(m1,m2)

array([[17., 15.],
       [45., 25.]])