In [22]:
import torch

In [23]:
# create Tensor
t = torch.FloatTensor([[[1,2,3,4], [10,20,30,40]], [[100,200,300,400], [50,60,70,80]], [[31,32,33,34],[20,21,22,23]]])
t

tensor([[[  1.,   2.,   3.,   4.],
         [ 10.,  20.,  30.,  40.]],

        [[100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.]],

        [[ 31.,  32.,  33.,  34.],
         [ 20.,  21.,  22.,  23.]]])

In [15]:
print(f"shape of t : {t.shape}")
print(f"size of t : {t.size()}")
print(f"mean of t : {t.mean()}")

shape of t : torch.Size([3, 2, 4])
size of t : torch.Size([3, 2, 4])
mean of t : 66.08333587646484


In [19]:
print(f"t.mean(dim=0) : \n {t.mean(dim=0)}\n")
print(f"t.mean(dim=1) : \n {t.mean(dim=1)}\n")
print(f"t.mean(dim=2) : \n {t.mean(dim=2)}\n")

t.mean(dim=0) : 
 tensor([[ 44.0000,  78.0000, 112.0000, 146.0000],
        [ 26.6667,  33.6667,  40.6667,  47.6667]])

t.mean(dim=1) : 
 tensor([[  5.5000,  11.0000,  16.5000,  22.0000],
        [ 75.0000, 130.0000, 185.0000, 240.0000],
        [ 25.5000,  26.5000,  27.5000,  28.5000]])

t.mean(dim=2) : 
 tensor([[  2.5000,  25.0000],
        [250.0000,  65.0000],
        [ 32.5000,  21.5000]])



In [21]:
print(f"t.max(dim=0) : \n {t.max(dim=0)}\n")
print(f"t.max(dim=1) : \n {t.max(dim=1)}\n")
print(f"t.max(dim=2) : \n {t.max(dim=2)}\n")
print(f"t.argmax(dim=2) : \n {t.argmax(dim=2)}\n")

t.max(dim=0) : 
 torch.return_types.max(
values=tensor([[100., 200., 300., 400.],
        [ 50.,  60.,  70.,  80.]]),
indices=tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]]))

t.max(dim=1) : 
 torch.return_types.max(
values=tensor([[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [ 31.,  32.,  33.,  34.]]),
indices=tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]))

t.max(dim=2) : 
 torch.return_types.max(
values=tensor([[  4.,  40.],
        [400.,  80.],
        [ 34.,  23.]]),
indices=tensor([[3, 3],
        [3, 3],
        [3, 3]]))

t.argmax(dim=2) : 
 tensor([[3, 3],
        [3, 3],
        [3, 3]])



In [30]:
print(f"==== t.view output ====")
print(f"original shape of t : {t.shape}")
print()
print(f"t.view([3, -1]) \n {t.view([3, -1])}\n")
print(f"t.view([2, -1]) \n {t.view([2, -1])}\n")
print(f"t.view([4, -1]) \n {t.view([4, -1])}\n")
print()
ft_view = t.view([1, 4, 6])
print(f"t.view([1, 4, 6]) \n {ft_view}\n")
print(f"reshape of t  :  {ft_view.shape}\n")


==== t.view output ====
original shape of t : torch.Size([3, 2, 4])

t.view([3, -1]) 
 tensor([[  1.,   2.,   3.,   4.,  10.,  20.,  30.,  40.],
        [100., 200., 300., 400.,  50.,  60.,  70.,  80.],
        [ 31.,  32.,  33.,  34.,  20.,  21.,  22.,  23.]])

t.view([2, -1]) 
 tensor([[  1.,   2.,   3.,   4.,  10.,  20.,  30.,  40., 100., 200., 300., 400.],
        [ 50.,  60.,  70.,  80.,  31.,  32.,  33.,  34.,  20.,  21.,  22.,  23.]])

t.view([4, -1]) 
 tensor([[  1.,   2.,   3.,   4.,  10.,  20.],
        [ 30.,  40., 100., 200., 300., 400.],
        [ 50.,  60.,  70.,  80.,  31.,  32.],
        [ 33.,  34.,  20.,  21.,  22.,  23.]])


t.view([1, 4, 6]) 
 tensor([[[  1.,   2.,   3.,   4.,  10.,  20.],
         [ 30.,  40., 100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.,  31.,  32.],
         [ 33.,  34.,  20.,  21.,  22.,  23.]]])

reshape of t  :  torch.Size([1, 4, 6])



In [33]:
t

tensor([[[  1.,   2.,   3.,   4.],
         [ 10.,  20.,  30.,  40.]],

        [[100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.]],

        [[ 31.,  32.,  33.,  34.],
         [ 20.,  21.,  22.,  23.]]])

In [41]:
t.squeeze()

tensor([[[  1.,   2.,   3.,   4.],
         [ 10.,  20.,  30.,  40.]],

        [[100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.]],

        [[ 31.,  32.,  33.,  34.],
         [ 20.,  21.,  22.,  23.]]])

In [44]:
print(t.unsqueeze(0))
print()
t.unsqueeze(0).shape

tensor([[[[  1.,   2.,   3.,   4.],
          [ 10.,  20.,  30.,  40.]],

         [[100., 200., 300., 400.],
          [ 50.,  60.,  70.,  80.]],

         [[ 31.,  32.,  33.,  34.],
          [ 20.,  21.,  22.,  23.]]]])



torch.Size([1, 3, 2, 4])

In [45]:
print(t.unsqueeze(1))
print()
t.unsqueeze(1).shape

tensor([[[[  1.,   2.,   3.,   4.],
          [ 10.,  20.,  30.,  40.]]],


        [[[100., 200., 300., 400.],
          [ 50.,  60.,  70.,  80.]]],


        [[[ 31.,  32.,  33.,  34.],
          [ 20.,  21.,  22.,  23.]]]])



torch.Size([3, 1, 2, 4])

In [46]:
print(t.unsqueeze(2))
print()
t.unsqueeze(2).shape

tensor([[[[  1.,   2.,   3.,   4.]],

         [[ 10.,  20.,  30.,  40.]]],


        [[[100., 200., 300., 400.]],

         [[ 50.,  60.,  70.,  80.]]],


        [[[ 31.,  32.,  33.,  34.]],

         [[ 20.,  21.,  22.,  23.]]]])



torch.Size([3, 2, 1, 4])

In [47]:
print(t.unsqueeze(-1))
print()
t.unsqueeze(-1).shape

tensor([[[[  1.],
          [  2.],
          [  3.],
          [  4.]],

         [[ 10.],
          [ 20.],
          [ 30.],
          [ 40.]]],


        [[[100.],
          [200.],
          [300.],
          [400.]],

         [[ 50.],
          [ 60.],
          [ 70.],
          [ 80.]]],


        [[[ 31.],
          [ 32.],
          [ 33.],
          [ 34.]],

         [[ 20.],
          [ 21.],
          [ 22.],
          [ 23.]]]])



torch.Size([3, 2, 4, 1])

In [48]:
# create Tensor1, 2, 3

t1 = torch.FloatTensor([[1,2,3,4], [10,20,30,40]])
t2 = torch.FloatTensor([[100,200,300,400], [50,60,70,80]])
t3 = torch.FloatTensor([[31,32,33,34],[20,21,22,23]])

In [51]:
print("====Concatenate of tensors====")

print(f"default cat : \n{torch.cat([t1,t2,t3])}\n")
print(f"dim 0 cat : \n{torch.cat([t1,t2,t3], dim=0)}\n")
print(f"dim 1 cat : \n{torch.cat([t1,t2,t3], dim=1)}\n")


====Concatenate of tensors====
default cat : 
tensor([[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [ 50.,  60.,  70.,  80.],
        [ 31.,  32.,  33.,  34.],
        [ 20.,  21.,  22.,  23.]])

dim 0 cat : 
tensor([[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [ 50.,  60.,  70.,  80.],
        [ 31.,  32.,  33.,  34.],
        [ 20.,  21.,  22.,  23.]])

dim 1 cat : 
tensor([[  1.,   2.,   3.,   4., 100., 200., 300., 400.,  31.,  32.,  33.,  34.],
        [ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  20.,  21.,  22.,  23.]])



In [54]:
print("====Stack of tensors====")

print(f"default stack : \n{torch.stack([t1,t2,t3])}\n")
print(f"dim 0 stack : \n{torch.stack([t1,t2,t3], dim=0)}\n")
print(f"dim 1 stack : \n{torch.stack([t1,t2,t3], dim=1)}\n")
print(f"dim 2 stack : \n{torch.stack([t1,t2,t3], dim=2)}\n")


====Stack of tensors====
default stack : 
tensor([[[  1.,   2.,   3.,   4.],
         [ 10.,  20.,  30.,  40.]],

        [[100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.]],

        [[ 31.,  32.,  33.,  34.],
         [ 20.,  21.,  22.,  23.]]])

dim 0 stack : 
tensor([[[  1.,   2.,   3.,   4.],
         [ 10.,  20.,  30.,  40.]],

        [[100., 200., 300., 400.],
         [ 50.,  60.,  70.,  80.]],

        [[ 31.,  32.,  33.,  34.],
         [ 20.,  21.,  22.,  23.]]])

dim 1 stack : 
tensor([[[  1.,   2.,   3.,   4.],
         [100., 200., 300., 400.],
         [ 31.,  32.,  33.,  34.]],

        [[ 10.,  20.,  30.,  40.],
         [ 50.,  60.,  70.,  80.],
         [ 20.,  21.,  22.,  23.]]])

dim 2 stack : 
tensor([[[  1., 100.,  31.],
         [  2., 200.,  32.],
         [  3., 300.,  33.],
         [  4., 400.,  34.]],

        [[ 10.,  50.,  20.],
         [ 20.,  60.,  21.],
         [ 30.,  70.,  22.],
         [ 40.,  80.,  23.]]])



In [55]:
torch.ones_like(t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
torch.ones(size=(2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [58]:
torch.zeros_like(t1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
torch.zeros(size=(2,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
t1 = torch.FloatTensor([[1,4,5], [5,6,7]])
t2 = torch.FloatTensor([[6,0], [-1,10], [3, -5]])
t1.matmul(t2)

tensor([[17., 15.],
        [45., 25.]])