# 1-1: Affine Functions with 1 Feature

### Code.1-1-1:Affine Function

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

# input : 하나의 feature라도 matrix 형태로 입력
x = tf.constant([[10.]])
# print(x.shape)   # 1x1

# x = tf.constant([[10.], [20.]])
# print(x.shape)    # 2x1

# dense layer (affine function)
dense = Dense(units = 1, activation='linear')
y_tf = dense(x)    # forward propagation + params initialization (실행마다 값이 다름. random parameter)

# get weight and bias
W, b = dense.get_weights()

# 행렬곱
y_man = tf.linalg.matmul(x, W) + b

# print results
print("==== Input/Weight/Bias ====")
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("b: {}\n{}\n".format(b.shape, b))

print("====Output====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

==== Input/Weight/Bias ====
x: (1, 1)
[[10.]]

W: (1, 1)
[[1.6498946]]

b: (1,)
[0.]

====Output====
y(Tensorflow): (1, 1)
[[16.498945]]

y(Manual): (1, 1)
[[16.498945]]



## Note
1. input은 matrix형태로 생성
2. unit 하나를 이용해서 affine function 하나를 수행
3. activation function = 생략 or 'linear'로 설정 = affine function을 거친 z 자체가 output이 됨.

### Code.1-1-2:Params Initialization

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant   # 내가 원하는 상수로 파라미터 초기화

# weight and bias setting
w, b = tf.constant(10.), tf.constant(20.)

w_init, b_init = Constant(w), Constant(b)     # 초기화해주는 object를 인스턴스로 선언 (tensor값이 아님)

print(w_init, b_init)

<keras.initializers.initializers.Constant object at 0x7d969f859120> <keras.initializers.initializers.Constant object at 0x7d969f85a800>


In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant   # 내가 원하는 상수로 파라미터 초기화

x = tf.constant([[10.]])     # input setting

# weight and bias setting
w, b = tf.constant(10.), tf.constant(20.)

w_init, b_init = Constant(w), Constant(b)     # 초기화해주는 object를 인스턴스로 선언

#
dense = Dense(units=1,
              activation='linear',
              kernel_initializer = w_init,
              bias_initializer=b_init)

y_tf = dense(x)

W, B = dense.get_weights()

# print results
print("W: {}\n{}\n".format(W.shape, W))
print("W: {}\n{}\n".format(B.shape, B))
print(y_tf)


W: (1, 1)
[[10.]]

W: (1,)
[20.]

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


# 1-2: Affine Functions with n Features

### Code.1-2-1: Affine Functions with n Features

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# 균등분포
x = tf.random.uniform(shape=(1, 10), minval=0, maxval = 10)   # 데이터는 1개 features는 10개. default value : (0,1) 사이의 값
print(x.shape, '\n', x)

dense = Dense(units=1, activation='linear')
y_tf = dense(x)
W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B   # broadcasting 되고있음.

# print results
print("==== Input/Weight/Bias ====")
print("x: {}\n{}\n".format(x.shape, x.numpy()))     # 1 x 10 Row Vector
print("W: {}\n{}\n".format(W.shape, W))     # 10 x 1 Column Vector
print("B: {}\n{}\n".format(B.shape, B))     # scalar

print("==== Outputs ====")
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

print(tf.math.equal(y_tf, y_man))

(1, 10) 
 tf.Tensor(
[[5.5196533 9.533964  0.5760932 0.7697964 9.92778   5.134696  6.5215864
  6.6457987 3.6749709 1.5754652]], shape=(1, 10), dtype=float32)
==== Input/Weight/Bias ====
x: (1, 10)
[[5.5196533 9.533964  0.5760932 0.7697964 9.92778   5.134696  6.5215864
  6.6457987 3.6749709 1.5754652]]

W: (10, 1)
[[-0.6120627 ]
 [-0.41574422]
 [ 0.68283993]
 [ 0.47522372]
 [ 0.42027992]
 [ 0.6728582 ]
 [ 0.7359436 ]
 [ 0.7296887 ]
 [-0.26886886]
 [ 0.55917436]]

B: (1,)
[0.]

==== Outputs ====
y(Tensorflow): (1, 1)
[[10.586268]]

y(manual): (1, 1)
[[10.586268]]

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


# 1-3: Activation Functions

### Code.1-3-1:Activaion Layers

1. activation function만 만드는 방법
2. affine function + activation function 같이 만드는 방법

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Activation
from tensorflow.math import exp, maximum     # sigmoid, relu

x = tf.random.normal(shape=(1,5))   # input setting (표준정규분포)

# activation layer 선언
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation (tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation (manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x)-exp(-x)) / (exp(x)+exp(-x))
y_relu_man = maximum(0, x)

# print results
print("x: {}\n{}\n".format(x.shape, x.numpy()))

print("Sigmoid(Tensorflow): {}\n{}\n".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}\n".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}\n".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(Manual): {}\n{}\n".format(y_relu_man.shape, y_relu_man.numpy()))


x: (1, 5)
[[ 1.2139647  1.0962358 -1.517538   1.490235   0.192643 ]]

Sigmoid(Tensorflow): (1, 5)
[[0.7709997  0.74955416 0.17982435 0.81611353 0.5480123 ]]

Sigmoid(Manual): (1, 5)
[[0.7709997  0.7495541  0.17982435 0.81611353 0.5480123 ]]

Tanh(Tensorflow): (1, 5)
[[ 0.8378649   0.7991428  -0.90826756  0.90336806  0.19029476]]

Tanh(Manual): (1, 5)
[[ 0.8378648   0.79914284 -0.9082676   0.9033679   0.1902948 ]]

ReLU(Tensorflow): (1, 5)
[[1.2139647 1.0962358 0.        1.490235  0.192643 ]]

ReLU(Manual): (1, 5)
[[1.2139647 1.0962358 0.        1.490235  0.192643 ]]



### Code.1-3-2:Activation in Dense Layer

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1,5))   # input setting (표준정규분포)

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

# get_weights

# print results
print("x : {}\n{}\n".format(x.shape, x.numpy()))
print("AN with Sigmoid : {}\n{}\n".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh : {}\n{}\n".format(y_tanh.shape, y_tanh.numpy()))
print("AN with ReLU : {}\n{}\n".format(y_relu.shape, y_relu.numpy()))

x : (1, 5)
[[-0.6227576   0.4088141   0.20009246  1.06027    -0.42903432]]

AN with Sigmoid : (1, 1)
[[0.6387753]]

AN with Tanh : (1, 1)
[[-0.47593927]]

AN with ReLU : (1, 1)
[[0.6243026]]



# 1-4: Artificial Neurons

### Code.1-4-1:Artificial Neurons

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation)  # imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man)-exp(-y_man)) / (exp(y_man)+exp(-y_man))
elif activation == 'relu':
  y_man = maximum(0, y_man)

print("Activation : ", activation)
print("y_tf : {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man : {}\n{}\n".format(y_man.shape, y_man.numpy()))
print(tf.math.equal(y_tf, y_man))

Activation :  relu
y_tf : (1, 1)
[[0.]]

y_man : (1, 1)
[[0.]]

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


# 1-5: Minibatches

### Code.1-5-1: Shapes of Dense Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10   # N : data의 개수, n_feature : feature의 개수
x = tf.random.normal(shape=(N, n_feature))
print(x.shape)

dense = Dense(units = 1, activation='relu')    # imp. an AN
y = dense(x)

W, B = dense.get_weights()

# print results
print("Shape of x : {}".format(x.shape))
print("Shape of W : {}".format(W.shape))
print("Shape of B : {}".format(B.shape))


(8, 10)
Shape of x : (8, 10)
Shape of W : (10, 1)
Shape of B : (1,)


!주의! : Minibatch의 사이즈(데이터의 개수 N)은 절대 weight, bias shape에 영향을 안 미친다!

### Code.1-5-2: Output calculations

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10   # N : data의 개수, n_feature : feature의 개수
x = tf.random.normal(shape=(N, n_feature))
# print(x.shape)

dense = Dense(units = 1, activation='relu')    # imp. an AN
y_tf = dense(x)     # forward propogation

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B     # forward propogation manually
y_man = maximum(0, y_man)

# print results
print("Shape of x : {}".format(x.shape))
print("Shape of W : {}".format(W.shape))
print("Shape of B : {}\n".format(B.shape))

print("Output (Tensorflow) : \n{}\n".format(y_tf.numpy()))
print("Output (Manual) : \n{}\n".format(y_man.numpy()))
print(tf.math.equal(y_tf, y_man))

Shape of x : (8, 10)
Shape of W : (10, 1)
Shape of B : (1,)

Output (Tensorflow) : 
[[0.7073164]
 [0.       ]
 [0.8786447]
 [0.       ]
 [1.7559942]
 [2.243993 ]
 [0.       ]
 [0.       ]]

Output (Manual) : 
[[0.7073164]
 [0.       ]
 [0.8786447]
 [0.       ]
 [1.7559942]
 [2.243993 ]
 [0.       ]
 [0.       ]]

tf.Tensor(
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]], shape=(8, 1), dtype=bool)


## __3D Tensor의 계산__

* Dense Layer는 2D tensor용으로 설계된 모델이다. <br>
* 3D tensor를 입력하기 위해서는 reshape를 통해서 2D tensor로 만들어줘야한다. <br>
* (batch_size, height, width) --> (batch_size, height*width)

In [ ]:
import tensorflow as tf

# Example 3D tensor with shape (batch_size, height, width)
input_tensor_3d = tf.random.normal((32, 10, 20))  # Batch size: 32, Height: 10, Width: 20

# Reshape the 3D tensor to a 2D tensor with shape (batch_size, height * width)
input_tensor_2d = tf.reshape(input_tensor_3d, (32, -1))  # -1 allows automatic calculation of the remaining dimension

# Define a Dense layer
dense_layer = tf.keras.layers.Dense(units=64, activation='relu')

# Apply the Dense layer to the reshaped 2D tensor
output = dense_layer(input_tensor_2d)