# 2-1: Dense Layers

### Code.2-1-1:Shapes of Dense Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10    # 학생 8명, 특징 10명
X = tf.random.normal(shape=(N,n_feature))    # Input Setting. Minibatch의 row 한개

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

# W.shape = (10, 3), b.shape = (1, 3) 이 되어야한다.

W,B = dense.get_weights()

print(f"==== Input, Weight, Bias ====")
print(f"X : {X.shape}")
print(f"W : {W.shape}")
print(f"B : {B.shape}")
print(f"Y : {Y_tf.shape}")


==== Input, Weight, Bias ====
X : (8, 10)
W : (10, 3)
B : (3,)
Y : (8, 3)


### Code.2-1-2: Output Calculations

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.math import exp
from tensorflow.linalg import matmul

N, n_feature = 4, 10

X = tf.random.normal(shape = (N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

print(f"Y(Tensorflow) : \n{Y_tf.numpy()} \n")

# 1 Caculate with matrix multiplication
W,B = dense.get_weights()
Z = matmul(X, W) + B
Y_matmul = 1/(1+exp(-Z))
print(f"Y(with Matrix multiplication): \n {Y_matmul.numpy()} \n")
print(tf.math.equal(Y_tf, Y_matmul).numpy(), " \n")

# 2 Calculate with dot product
Y_man_vec = np.zeros((N,n_neuron))
#Y_man_vec = np.zeroslike(X)
print(Y_man_vec, " \n")

for x_idx in range(N):
  x = X[x_idx]       # 이때 형태봐보고

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]     # w, b 형태 보자

    z = tf.reduce_sum(w*x) + b        # 이부분 설명 다시 들어보기
    a = 1 / (1+exp(-z))

    Y_man_vec[x_idx, nu_idx] = a

print(f"Y(with dot product) : \n{Y_man_vec} \n")

Y(Tensorflow) : 
[[0.76273596 0.7518877  0.95685875]
 [0.7451977  0.21340722 0.6409643 ]
 [0.7067717  0.3352568  0.4505635 ]
 [0.23157226 0.6616104  0.23050532]] 

Y(with Matrix multiplication): 
 [[0.76273596 0.7518876  0.9568588 ]
 [0.7451977  0.2134072  0.6409643 ]
 [0.7067717  0.33525676 0.45056352]
 [0.23157227 0.6616105  0.23050533]] 

[[ True False False]
 [ True False  True]
 [ True False False]
 [False False False]]  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]  

Y(with dot product) : 
[[0.76273596 0.75188762 0.95685881]
 [0.74519771 0.2134072  0.64096433]
 [0.70677167 0.33525676 0.45056352]
 [0.23157227 0.66161048 0.23050533]] 



# 2-2: Cascaded Dense Layers

### Code.2-2-1:Shapes of Cascaded Dense Layers

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]

dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

print(f"X: {X.shape}")
print(f"A1: {A1.shape}")
print(f"Y: {Y.shape}")
print()
# 컬럼의 개수만 달라짐. 데이터를 표현해주는 feature, neuron의 개수가 달라짐.

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print(f"W1 shape : {W1.shape}")
print(f"B1 shape : {B1.shape}")
print(f"A1 shape : {A1.shape}")
print()
print(f"W2 shape : {W2.shape}")
print(f"B2 shape : {B2.shape}")
print(f"Y shape : {Y.shape}")

# shape의 개수 -->  data의 개수, neuron의 개수, feature의 개수 파악하면서 복습!

X: (4, 10)
A1: (4, 3)
Y: (4, 5)

W1 shape : (10, 3)
B1 shape : (3,)
A1 shape : (4, 3)

W2 shape : (3, 5)
B2 shape : (5,)
Y shape : (4, 5)


### Code.2-2-2: Dense Layers with Python List

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = list(range(10,101,10))

dense_layers = list()

for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

for i, dense in enumerate(dense_layers):
  X = dense(X)
  print(f"After dense layer {i+1} : {X.shape}\n")

After dense layer 1 : (4, 10)

After dense layer 2 : (4, 20)

After dense layer 3 : (4, 30)

After dense layer 4 : (4, 40)

After dense layer 5 : (4, 50)

After dense layer 6 : (4, 60)

After dense layer 7 : (4, 70)

After dense layer 8 : (4, 80)

After dense layer 9 : (4, 90)

After dense layer 10 : (4, 100)



### Code.2-2-3: Output calculations

In [ ]:
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)   # copy함수
print(f"Input : {X.shape} \n")

n_neurons = [3, 4, 5]

dense_layers = list()
for nu in n_neurons:
  dense = Dense(units=nu, activation='sigmoid')
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for i, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()
  W.append(w)
  B.append(b)
print(f"Output(Y_tensorflow) : {X.shape} \n {X.numpy()}\n")

# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w,b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1 / (1+exp(-X_cp))

print(f"Output(Y_manual) : {X_cp.shape} \n{X_cp.numpy()}\n")
print(tf.math.equal(X,X_cp).numpy())

Input : (4, 10) 

Output(Y_tensorflow) : (4, 5) 
 [[0.39475682 0.5356454  0.54128385 0.45982313 0.76339406]
 [0.39984536 0.5404337  0.549554   0.46724692 0.76669014]
 [0.39723817 0.56423295 0.5729208  0.46945578 0.7522398 ]
 [0.40080285 0.5551429  0.5655172  0.47169673 0.7602956 ]]

Output(Y_manual) : (4, 5) 
[[0.39475682 0.5356454  0.54128385 0.45982316 0.76339406]
 [0.39984536 0.5404337  0.54955405 0.46724695 0.7666902 ]
 [0.39723814 0.56423295 0.5729208  0.4694558  0.75223976]
 [0.40080285 0.5551428  0.5655172  0.47169676 0.76029557]]

[[ True  True  True False  True]
 [ True  True False False False]
 [False  True  True False False]
 [ True False  True False False]]


# 2-3:Model Implementation

### Code.2-3-1: Model Implementation with Sequential Method

### Code.2-3-2:Model Implementation with Model-subclassing

### Code.2-3-3:Forward Propagation of Models

### Code.2-3-4:Layers in Models

### Code.2-3-5:Trainable Variables in Models