# 5-1: Conv Layers

### Code.5-1-1: Shapes of Conv Layers

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, H, W, C = 32, 28, 28, 5                                                        # 5채널 28*28 크기의 이미지 32장
n_filter = 10                                                                     # kernel과 filter는 같은 말. 컨볼루젼 연산의 가중치 역할을 하는 것. weights
k_size = 3                                                                        # kernel size와 window size는 같다. 2D연산 이므로 3*3*5 shape을 가진다.

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, H, W, C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print(f"images.shape : {images.shape}\n")
print(f"W.shape : {W.shape}\n")
print(f"B.shape : {B.shape}\n")
print(f"Y.shape : {Y.shape}\n")

images.shape : (32, 28, 28, 5)

W.shape : (3, 3, 5, 10)

B.shape : (10,)

Y.shape : (32, 26, 26, 10)



### Code.5-1-2: Correlation Calculation

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y =conv(images)
print(f"Y(Tensorflow): \n{y.numpy().squeeze()}\n", )

W, B = conv.get_weights()


#####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size, j : j+k_size]
    y_man[i,j] = np.sum(window*W) + B

print(f"Y(Manual): \n{y_man}\n")

Y(Tensorflow): 
[[-0.830198  -0.6050263 -0.6423546]
 [-1.2197508 -1.239354  -1.0386194]
 [-0.6761166 -1.1174173 -1.2434435]]

Y(Manual): 
[[-0.83019799 -0.6050263  -0.64235455]
 [-1.21975076 -1.23935401 -1.0386194 ]
 [-0.67611659 -1.11741734 -1.24344349]]



### Code.5-1-3: Correlation with n-channel

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y_tf = conv(images)
print(f"Y (Tensorflow) : \n{Y_tf.numpy().squeeze()}\n")

W, B = conv.get_weights()

### Manually Calculation
images = images.numpy().squeeze()
W = W.squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i:i+k_size, j:j+k_size, :]
    Y_man[i, j] = np.sum(W*window) + B

print(f"Y (Manual) : \n{Y_man}\n")

Y (Tensorflow) : 
[[ 0.0245553   0.23712136  0.10675966]
 [ 0.47287887 -0.05116513  0.04318195]
 [ 0.5239473   0.5310539   0.09158444]]

Y (Manual) : 
[[ 0.02455524  0.23712137  0.10675962]
 [ 0.47287887 -0.05116522  0.04318195]
 [ 0.5239473   0.5310539   0.09158444]]



# 5-2: Conv Layer with Filters

### Code.5-2-1: Shapes with Filters

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Image: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Image: (32, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


### Code.5-2-2: Computations with Filters

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3                                                     # 1개 데이터, 5*5이미지 3채널
n_filter = 5
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N,n_H,n_W,n_C))

# Forward Propogation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
# print(f"Y.shape : {Y.shape}\n")
# print(f"Y : \n{Y.numpy().squeeze()}\n")

Y = np.transpose(Y.numpy().squeeze(), (2,0,1))                                    # (1*5*5*3) → (1*2*2*5) → (5*2*2)
print(f"Y.transpose.shape : {Y.shape}\n")                                         # filter와의 for문을 이용한 연산에서 편의를 위해 (C, H, W)로 shape를 정리해줌.
print(f"Y.transpose : \n{Y}\n")


# Forward Propogation(Manually)
W, B = conv.get_weights()
# print(f"W.shape : {W.shape}\nB.shape : {B.shape}")

images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_B = B[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h : h+k_size, w : w+k_size, :]
      conv = np.sum(window*c_W) + c_B

      Y_man[h, w, c] = conv


Y_man = np.transpose(Y_man, (2,0,1))
print(f"Y_man.shape : {Y_man.shape}\n")                                          # (2, 2, 5)  -->  (5, 2, 2)
print(f"Y_man : \n{Y_man}\n")


Y.transpose.shape : (5, 2, 2)

Y.transpose : 
[[[ 0.40800795  0.51187825]
  [ 0.43726444  0.19979002]]

 [[ 0.9980401   0.6667397 ]
  [ 1.0772643   1.153334  ]]

 [[-0.3015676  -0.29802585]
  [ 0.0101362  -0.48154038]]

 [[-0.53960687 -0.10193698]
  [ 0.33895004  0.26196137]]

 [[-0.07440612 -0.23563303]
  [-0.67135966 -0.56425136]]]

Y_man.shape : (5, 2, 2)

Y_man : 
[[[ 0.40800798  0.51187831]
  [ 0.43726438  0.19978999]]

 [[ 0.99804008  0.66673976]
  [ 1.07726443  1.1533339 ]]

 [[-0.30156758 -0.29802579]
  [ 0.01013619 -0.48154041]]

 [[-0.53960687 -0.10193704]
  [ 0.33895004  0.2619614 ]]

 [[-0.07440616 -0.23563306]
  [-0.67135966 -0.56425136]]]



# Conv Layers with Activation Functions

### Code.5-3-1: Conv Layers with Activation Functions

In [18]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 6
k_size = 4
images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

# Forward Propogation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size, activation = 'sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print(f"Y.shape : {Y.shape}\n")
print(f"Y(Tensorflow) : \n{Y}\n")

W, b = conv.get_weights()
print(f"W.shape : {W.shape}\nB.shape : {b.shape}\n")

# Forward Propogation (Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))

for c in range(n_filter):
  c_W = W[:, :, :, c]
  c_b = b[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size, :]
      conv = np.sum(window*c_W) + c_b

      Y_man[h, w, c] = conv

Y_man = np.transpose(Y_man, (2,0,1))
A_man = 1 / (1 + np.exp(-Y_man))

print(f"Y_man.shape : {Y.shape}\n")
print(f"Y(Manual) : \n{A_man}\n")

Y.shape : (6, 2, 2)

Y(Tensorflow) : 
[[[0.47132337 0.3890956 ]
  [0.35898736 0.36432558]]

 [[0.6902412  0.69163144]
  [0.6303386  0.65719485]]

 [[0.5430471  0.52312183]
  [0.39020914 0.45081493]]

 [[0.32837832 0.32438058]
  [0.3784731  0.41582578]]

 [[0.3786924  0.32480136]
  [0.39660394 0.38579607]]

 [[0.65224224 0.6360031 ]
  [0.6848871  0.64125746]]]

W.shape : (4, 4, 3, 6)
B.shape : (6,)

Y_man.shape : (6, 2, 2)

Y(Manual) : 
[[[0.47132338 0.38909562]
  [0.35898735 0.36432557]]

 [[0.69024119 0.69163149]
  [0.63033858 0.65719482]]

 [[0.54304711 0.52312184]
  [0.39020913 0.45081494]]

 [[0.32837831 0.32438059]
  [0.37847308 0.41582575]]

 [[0.3786924  0.32480135]
  [0.39660397 0.38579609]]

 [[0.6522422  0.63600306]
  [0.68488716 0.64125746]]]



# 5-4: Models with Conv Layers

### Code.5-4-1: Models with Sequential Method

In [27]:
from tensorflow.python.ops.variables import trainable_variables
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_filters = [10, 20, 30]

model = Sequential()
model.add(Conv2D(filters=n_filters[0], kernel_size=3, activation='relu'))
model.add(Conv2D(filters=n_filters[1], kernel_size=3, activation='relu'))
model.add(Conv2D(filters=n_filters[2], kernel_size=3, activation='relu'))

x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)

print(f"Input shape : {x.shape}\n")
print(f"Output shape : {predictions.shape}\n")

for i, layer in enumerate(model.layers):
  W, B = layer.get_weights()
  print(f"layer{i} W, B shape : {W.shape, B.shape}")

print('\n------------------\n')

trainable_variables = model.trainable_variables

for train_var in trainable_variables:
  print(train_var.shape)

Input shape : (32, 28, 28, 3)

Output shape : (32, 22, 22, 30)

layer0 W, B shape : ((3, 3, 3, 10), (10,))
layer1 W, B shape : ((3, 3, 10, 20), (20,))
layer2 W, B shape : ((3, 3, 20, 30), (30,))

------------------

(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


### Code.5-4-2: Models with Model Sub-classing

In [32]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_filters = [10, 20, 30]

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()
    global n_filters

    self.conv_layers = []
    for n_filter in n_filters:
      self.conv_layers.append(Conv2D(filters=n_filter, kernel_size=3, activation='relu'))

  def fit(self, x):                                                              # __call__ 로 할 경우, model(x)로 바로 해당 함수를 실행할 수 있음.
    print(f"Input shape : {x.shape}\n")

    print("======== Conv Layers ========\n")
    for conv_layer in self.conv_layers:
      x = conv_layer(x)
      W, B = conv_layer.get_weights()
      print(f"Output shape : {x.shape}")
      print(f"W, B shape : {W.shape, B.shape}")

    return x


model = TestModel()
x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model.fit(x)


Input shape : (32, 28, 28, 3)

======== Conv Layers ========

Output shape : (32, 26, 26, 10)
W, B shape : ((3, 3, 3, 10), (10,))
Output shape : (32, 24, 24, 20)
W, B shape : ((3, 3, 10, 20), (20,))
Output shape : (32, 22, 22, 30)
W, B shape : ((3, 3, 20, 30), (30,))


In [35]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Model

n_filters = [10, 20, 30]

class TestModel(Model):

  def __init__(self):
    super(TestModel, self).__init__()
    global n_filters

    self.conv1 = Conv2D(filters=n_filters[0], kernel_size=3, activation='relu')
    self.conv2 = Conv2D(filters=n_filters[1], kernel_size=3, activation='relu')
    self.conv3 = Conv2D(filters=n_filters[2], kernel_size=3, activation='relu')

  def call(self, x):
    x = self.conv1(x)
    x = self.conv2(x)
    x = self.conv3(x)

    return x


model = TestModel()
x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)
print(f"Y shape : {predictions.shape}")

Y shape : (32, 22, 22, 30)
