# 6-1: 1D Max/Avg Pooling
- Temporal Data

### Code.6-1-1: Max Pooling
 - [tf.keras.layers.MaxPooling1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling1D)

In [18]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

# Length, filter_size, stride
L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))                                            # (L,)이 아니라 (1,L,1)로 해주는 이유 : 3차원이상인 tensor 형태로 통일시키기 위함.
print(f"x shape : {x.shape}\n{x}\n")

pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)
print(f"pooled_max shape : {pooled_max.shape}")
print(f"pooled_max (Tensorflow) : \n{pooled_max.numpy().flatten()}\n")


# Manually Calculation
x = x.numpy().flatten()
pooled_max_man = np.zeros(shape=(L - f + 1,))                                    # Manual로 계산할때는 (L-f+1,)로 계산해야한다.
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i]=np.max(window)

print(f"pool_max (Manual) : \n{pooled_max_man}\n")


x shape : (1, 10, 1)
[[[-0.43122596]
  [ 0.6752659 ]
  [-1.561275  ]
  [-0.04129217]
  [-0.44925028]
  [ 0.44253048]
  [-1.4825224 ]
  [-0.43200547]
  [-1.9314715 ]
  [ 0.12660249]]]

pooled_max shape : (1, 9, 1)
pooled_max (Tensorflow) : 
[ 0.6752659   0.6752659  -0.04129217 -0.04129217  0.44253048  0.44253048
 -0.43200547 -0.43200547  0.12660249]

pool_max (Manual) : 
[ 0.67526591  0.67526591 -0.04129217 -0.04129217  0.44253048  0.44253048
 -0.43200547 -0.43200547  0.12660249]



In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

# Length, filter_size, stride
L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
print(f"x shape : {x.shape}\n")
print(f"x : \n{x.numpy().flatten()}\n")

pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)
print(f"pooled_max shape : {pooled_max.shape}")
print(f"pooled_max (Tensorflow) : \n{pooled_max.numpy().flatten()}\n")


# Manually Calculation
x = x.numpy().flatten()
pooled_max_man = np.zeros(shape=(L - f + 1,))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i]=np.max(window)

print(f"pool_max (Manual) : \n{pooled_max_man}\n")


x shape : (1, 10, 1)

x : 
[ 2.3937273   0.24467704  1.214477    0.1923746   0.8627955   0.6289198
 -0.8608641  -0.33826697 -0.19088206 -0.01867449]

pooled_max shape : (1, 9, 1)
pooled_max (Tensorflow) : 
[ 2.3937273   1.214477    1.214477    0.8627955   0.8627955   0.6289198
 -0.33826697 -0.19088206 -0.01867449]

pool_max (Manual) : 
[ 2.3937273   1.21447694  1.21447694  0.86279547  0.86279547  0.62891978
 -0.33826697 -0.19088206 -0.01867449]



### Code.6-1-2: Average Pooling
- [tf.keras.layers.AveragePooling1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling1D)

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 4, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print(f"x : {x.shape}\n{x.numpy().flatten()}\n")
print(f"pooled average : {pooled_avg.shape}\n{pooled_avg.numpy().flatten()}\n")


# Manually
x = x.numpy().flatten()
pooled_avg_man = np.zeros(shape=(L-f+1,))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i]=np.mean(window)

print(f"pooled average (manually) : {pooled_avg_man.shape}")
print(f"{pooled_avg_man}\n")


x : (1, 10, 1)
[-0.24032456 -0.14212467  0.21424757 -0.63210255  0.07188271 -0.07254945
 -1.4946982  -0.02499197 -0.17738146  0.08539703]

pooled average : (1, 7, 1)
[-0.20007604 -0.12202424 -0.10463043 -0.53186685 -0.38008922 -0.44240528
 -0.40291864]

pooled average (manually) : (7,)
[-0.20007604 -0.12202424 -0.10463043 -0.53186685 -0.38008922 -0.44240528
 -0.40291864]



# 6-2: 2D Max/Avg Pooling
- Spatial Data

### Code.6-2-1: 2D Max Pooling
- [tf.keras.layers.MaxPooling2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling2D)

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)

pooled_max = pool_max(x)
print(f"pooled max (Tensorflow) : {pooled_max.numpy().squeeze().shape}\n{pooled_max.numpy().squeeze()}\n")

# print(f"pooled max (Original) : {pooled_max.numpy().shape}\n{pooled_max.numpy()}\n")
# print(f"pooled max (Squeeze) : {pooled_max.numpy().squeeze().shape}\n{pooled_max.numpy().squeeze()}\n")
# print(f"pooled max (Flatten) : {pooled_max.numpy().flatten().shape}\n{pooled_max.numpy().flatten()}\n")


## Manually Calculating
x = x.numpy().squeeze()

pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window)

print(f"pooled max (Manually) : {pooled_max_man.shape}\n{pooled_max_man}\n")

pooled max (Tensorflow) : (4, 4)
[[ 2.1722922   2.1722922   1.5424674   1.2357292 ]
 [-0.14225027 -0.14225027  0.47841164  1.2357292 ]
 [ 0.34107068  0.34107068  0.3483935   0.8234301 ]
 [ 0.34107068  2.4434972   2.4434972   0.85322094]]

pooled max (Manually) : (4, 4)
[[ 2.17229223  2.17229223  1.54246736  1.23572922]
 [-0.14225027 -0.14225027  0.47841164  1.23572922]
 [ 0.34107068  0.34107068  0.3483935   0.82343012]
 [ 0.34107068  2.44349718  2.44349718  0.85322094]]



### Code.6-2-2: 2D Average Pooling
- [tf.keras.layers.AveragePooling2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling2D)

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)

pooled_avg = pool_avg(x)
print(f"pooled_avg (Tensorflow) : {pooled_avg.numpy().squeeze().shape}\n{pooled_avg.numpy().squeeze()}\n")


# Manually
x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1, n_W-f+1))
for i in range(n_H-f+1):
  for j in range(n_W-f+1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.mean(window)

print(f"pooled_avg (Manually) : {pooled_avg_man.shape}\n{pooled_avg_man}\n")

pooled_avg (Tensorflow) : (4, 4)
[[ 0.53307635 -0.24055484 -0.6592576  -0.24083778]
 [-0.05978495 -0.41976872 -0.616948   -0.34557715]
 [-0.7492107  -0.20203416  0.34496284  0.16741294]
 [-0.2804139  -0.17046693  0.02412523  0.26640508]]

pooled_avg (Manually) : (4, 4)
[[ 0.53307635 -0.24055484 -0.65925759 -0.24083778]
 [-0.05978495 -0.41976872 -0.61694801 -0.34557715]
 [-0.74921072 -0.20203416  0.34496284  0.16741294]
 [-0.2804139  -0.17046693  0.02412523  0.26640508]]



# 6-3: 3D Max/Avg Pooling
- 2D Spatial Data with channels(layers)

### Code.6-3-1: 3D Max Pooling

In [73]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3                                                     # 채널이 1개인 것(2D)에서 채널이 3개인 것으로 차원이 증가해도
f, s = 2, 2                                                                       # H, W가 그대로이고, 2D Max Pooling Layer를 사용한다.

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
print(f"x : {x.shape}\n")
# print(f"{np.transpose(x.numpy().squeeze(), (2,0,1))}\n")

pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)
print(f"pooled_max : {pooled_max.shape}\n")
print(f"{np.transpose(pooled_max.numpy().squeeze(), (2,0,1))}\n")


# Manually
x = x.numpy().squeeze()
print(f"x : {x.shape}\n")

pooled_max_man = np.zeros(shape=((n_H-f)//s+1, (n_W-f)//s+1, n_C))
print(f"pooled_max_man : {pooled_max_man.shape}\n")

for c in range(n_C):
  for i in range(0, n_H-f+1, s):
    for j in range(0, n_W-f+1, s):
      window = x[i:i+f, j:j+f, c]
      pooled_max_man[i//s, j//s, c] = np.max(window)

print(f"{np.transpose(pooled_max_man, (2, 0, 1))}\n")


x : (1, 5, 5, 3)

pooled_max : (1, 2, 2, 3)

[[[1.3993345  1.7508168 ]
  [2.4826648  0.32386592]]

 [[2.0015414  2.4381943 ]
  [1.1877382  0.08571324]]

 [[1.5210338  0.6301474 ]
  [2.7513711  0.38949075]]]

x : (5, 5, 3)

pooled_max_man : (2, 2, 3)

[[[1.39933455 1.75081682]
  [2.48266482 0.32386592]]

 [[2.00154138 2.43819427]
  [1.18773818 0.08571324]]

 [[1.52103376 0.6301474 ]
  [2.75137115 0.38949075]]]



### Code.6-3-2: 3D Average Pooling
- [tf.keras.layers.AveragePooling3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling3D)

In [71]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 10, 10, 3
f, s = 3, 3

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
print(f"x : {x.shape}\n")
# print(f"{np.transpose(x.numpy().squeeze(), (2, 0, 1))}\n")

pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)
print(f"pooled_avg : {pooled_avg.shape}\n")
print(f"{np.transpose(pooled_avg.numpy().squeeze(), (2, 0, 1))}\n")


# Manually
x = x.numpy().squeeze()

n_H_ = (n_H-f)//s + 1
n_W_ = (n_W-f)//s + 1

pooled_avg_man = np.zeros(shape=(n_H_, n_W_, n_C))
print(f"pooled_avg_man : {pooled_avg_man.shape}")

for c in range(n_C):
  for i in range(0, n_H-f+1, s):
    for j in range(0, n_W-f+1, s):
        window = x[i:i+f, j:j+f, c]
        pooled_avg_man[i//s, j//s, c] = np.mean(window)

print(f"{np.transpose(pooled_avg_man, (2, 0, 1))}")

x : (1, 10, 10, 3)

pooled_avg : (1, 3, 3, 3)

[[[ 0.31417027  0.12428641  0.29245755]
  [ 0.07060012 -0.01831888  0.4367933 ]
  [ 0.23851933  0.11482716 -0.1204742 ]]

 [[-0.02771397 -0.42231902  0.05370123]
  [ 0.4910371  -0.15594688  0.5520206 ]
  [-0.52877414  0.2620455  -0.053348  ]]

 [[ 0.23525852 -0.24930975  0.10347292]
  [ 0.0055281  -0.17839466  0.2830283 ]
  [-0.00307893  0.32387006  0.07724789]]]

pooled_avg_man : (3, 3, 3)
[[[ 0.31417024  0.12428641  0.29245758]
  [ 0.07060012 -0.01831888  0.43679336]
  [ 0.23851936  0.11482717 -0.1204742 ]]

 [[-0.02771397 -0.42231902  0.05370122]
  [ 0.4910371  -0.15594688  0.55202061]
  [-0.5287742   0.2620455  -0.053348  ]]

 [[ 0.23525852 -0.24930972  0.10347291]
  [ 0.0055281  -0.17839466  0.28302827]
  [-0.00307893  0.32387009  0.07724789]]]


# (+) Plus: 4D Max/Avg Pooling
- 3D data (spatial or spatio-temporal) like RGB video

### (+) Code.1: 4D Max Pooling
- [tf.keras.layers.MaxPooling3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling3D)

In [70]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling3D

N, n_D, n_H, n_W, n_C = 1, 10, 10, 10, 3                                         # Depth : 깊이, Timestamp가 될 수도 있다.
f, s = 5, 3

x = tf.random.normal(shape=(N, n_D, n_H, n_W, n_C))
print(f"x : {x.shape}\n")

pool_max = MaxPooling3D(pool_size=f, strides=s)                                  # f는 (f, f, f)와 같다.
pooled_max = pool_max(x)
print(f"pooled_max : {pooled_max.shape}\n")
print(f"{np.transpose(pooled_max.numpy().squeeze(), (3, 0, 1, 2))}\n")


# Manually
x = x.numpy().squeeze()
n_D_ = (n_D - f)//s + 1
n_H_ = (n_H - f)//s + 1
n_W_ = (n_W - f)//s + 1

pooled_max_man = np.zeros(shape=(n_D_, n_H_, n_W_, n_C))
print(f"pooled_max_man : {pooled_max_man.shape}\n")

for c in range(n_C):
  for i in range(0, n_D-f+1, s):
    for j in range(0, n_H-f+1, s):
      for k in range(0, n_W-f+1, s):
        window = x[i:i+f, j:j+f, k:k+f, c]
        pooled_max_man[i//s, j//s, k//s, c] = np.max(window)

print(f"{np.transpose(pooled_max_man, (3, 0, 1, 2))}\n")


x : (1, 10, 10, 10, 3)

pooled_max : (1, 2, 2, 2, 3)

[[[[2.5635805 2.822126 ]
   [2.338618  2.822126 ]]

  [[2.2401423 2.822126 ]
   [2.8780203 2.822126 ]]]


 [[[3.3652468 2.2397454]
   [2.033714  2.3904128]]

  [[3.3652468 2.8737915]
   [1.8934376 2.8737915]]]


 [[[1.9567736 1.8670801]
   [2.2882318 2.1148198]]

  [[2.8922582 2.5602703]
   [2.8922582 2.6428447]]]]

pooled_max_man : (2, 2, 2, 3)

[[[[2.56358051 2.82212591]
   [2.33861804 2.82212591]]

  [[2.24014235 2.82212591]
   [2.87802029 2.82212591]]]


 [[[3.36524677 2.23974538]
   [2.03371406 2.39041281]]

  [[3.36524677 2.87379146]
   [1.89343762 2.87379146]]]


 [[[1.95677364 1.86708009]
   [2.28823185 2.11481977]]

  [[2.89225817 2.56027031]
   [2.89225817 2.64284468]]]]



### (+) Code.2: 4D Average Pooling

In [69]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling3D

N, n_D, n_H, n_W, n_C = 1, 5, 8, 8, 3
f, s = (4, 3, 2), (1, 2, 3)

x = tf.random.normal(shape=(N, n_D, n_H, n_W, n_C))
print(f"x : {x.shape}\n")

pool_avg = AveragePooling3D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)
print(f"pooled_avg : {pooled_avg.shape}\n")
print(f"{np.transpose(pooled_avg.numpy().squeeze(), (3, 0, 1, 2))}\n")


# Manually
x = x.numpy().squeeze()
n_D_ = (n_D-f[0])//s[0] + 1
n_H_ = (n_H-f[1])//s[1] + 1
n_W_ = (n_W-f[2])//s[2] + 1

pooled_avg_man = np.zeros(shape=(n_D_, n_H_, n_W_, n_C))
print(f"pooled_avg_man : {pooled_avg_man.shape}\n")

for c in range(n_C):
  for i in range(0, n_D-f[0]+1, s[0]):
    for j in range(0, n_H-f[1]+1, s[1]):
      for k in range(0, n_W-f[2]+1, s[2]):
        window = x[i:i+f[0], j:j+f[1], k:k+f[2], c]
        pooled_avg_man[i//s[0], j//s[1], k//s[2], c] = np.mean(window)

print(f"{np.transpose(pooled_avg_man, (3, 0, 1, 2))}\n")


x : (1, 5, 8, 8, 3)

pooled_avg : (1, 2, 3, 3, 3)

[[[[ 0.3855799   0.20686609 -0.37611893]
   [ 0.01053302  0.26205066 -0.27821973]
   [ 0.02644368  0.21180515 -0.16520283]]

  [[ 0.25694868  0.2227795  -0.46872637]
   [-0.04423368  0.31731036 -0.25706112]
   [ 0.10359189 -0.0092252   0.06347651]]]


 [[[ 0.0575168   0.1040568   0.17628284]
   [-0.02473103  0.08699621 -0.17372768]
   [-0.14216419  0.01594133 -0.16913088]]

  [[ 0.14970036  0.3313696   0.16667838]
   [ 0.03489717  0.19907665 -0.07286894]
   [-0.07145699  0.04714195 -0.14589334]]]


 [[[-0.5343695  -0.24611793 -0.08207122]
   [-0.03161182 -0.37233362 -0.03181702]
   [ 0.12775365  0.18132891  0.17628801]]

  [[-0.38478348 -0.13586152  0.08787632]
   [-0.11093543 -0.06928793  0.11357561]
   [ 0.05550773  0.1180866   0.22368939]]]]

pooled_avg_man : (2, 3, 3, 3)

[[[[ 0.38557991  0.20686609 -0.37611893]
   [ 0.01053302  0.26205066 -0.27821973]
   [ 0.0264437   0.21180515 -0.16520281]]

  [[ 0.25694874  0.2227795  -0.468726