# 6-4: Padding

### Code.6-4-1: ZeroPadding1D Layer
- [tf.keras.layers.ZeroPadding1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ZeroPadding1D)
- Zero-padding layer for 1D input (e.g. temporal sequence).

In [20]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding1D

x = tf.random.uniform(shape=(1, 10, 1), minval=0, maxval=10, dtype=tf.int64)

print(f"{x.numpy().squeeze().shape}")
print("  ↓")
print(f"{ZeroPadding1D(padding=2)(x).numpy().squeeze().shape}\n")


print(f"{x.numpy().squeeze()}\n")

print(f"{ZeroPadding1D(padding=2)(x).numpy().squeeze()}\n")


(10,)
  ↓
(14,)

[2 3 2 8 4 5 3 9 6 7]

[0 0 2 3 2 8 4 5 3 9 6 7 0 0]



### Code.6-4-2: ZeroPadding2D Layer
- [tf.keras.layers.ZeroPadding2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ZeroPadding2D)
- Zero-padding layer for 2D input (e.g. picture).

In [19]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding2D

x = tf.random.uniform(shape=(1, 5, 5, 1), minval=0, maxval=10, dtype=tf.int64)

print(x.numpy().squeeze().shape)
print("  ↓")
print(ZeroPadding2D(padding=(1, 2))(x).numpy().squeeze().shape)

print(f"\n{x.numpy().squeeze()}\n")

print(f"{ZeroPadding2D(padding=(1, 2))(x).numpy().squeeze()}\n")


(5, 5)
  ↓
(7, 9)

[[5 0 7 8 7]
 [3 3 3 6 0]
 [5 1 1 3 1]
 [9 4 7 6 5]
 [6 6 9 3 2]]

[[0 0 0 0 0 0 0 0 0]
 [0 0 5 0 7 8 7 0 0]
 [0 0 3 3 3 6 0 0 0]
 [0 0 5 1 1 3 1 0 0]
 [0 0 9 4 7 6 5 0 0]
 [0 0 6 6 9 3 2 0 0]
 [0 0 0 0 0 0 0 0 0]]



### Code.6-4-3: ZeroPadding3D Layer
- [tf.keras.layers.ZeroPadding3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ZeroPadding3D)
- Zero-padding layer for 3D data (spatial or spatio-temporal).

In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding3D

x = tf.random.uniform(shape=(1, 1, 2, 2, 1), minval=0, maxval=10, dtype=tf.int64)

print(f"{x.numpy().squeeze().shape}")
print("  ↓")
zero_pad = ZeroPadding3D(padding=(1, 2, 2))(x).numpy().squeeze()
print(f"{zero_pad.shape}\n")
print(f"{zero_pad}\n")


(2, 2)
  ↓
(3, 6, 6)

[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 4 4 0 0]
  [0 0 7 1 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]



### (+) Code: Padding and Strides in Conv2D Layers

In [28]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))

# padding ('valid') : 패딩을 넣지 않겠다는 의미.
conv1 = Conv2D(filters=3, kernel_size=5, padding='valid', strides=1)
# padding ('same') : input size와 동일하도록 padding을 넣는다는 의미.
# padding이 얼마나 들어가는지는? : n_H + 2p - f = n_H 공식으로 p를 구할 수 있다.
conv2 = Conv2D(filters=3, kernel_size=5, padding='same', strides=1)

# 일반적으로는 (n_H - f) // s + 1의 공식으로 output shape을 구하면된다.
print(f"x (valid padding) : {conv1(images).shape}\n") #{conv1(images).numpy()}\n
print(f"x (same padding) : {conv2(images).shape}\n")  #{conv2(images).numpy()}\n

# (n_H + 2p - f)//s + 1 의 공식으로 output shape을 구하면 된다.
conv1 = Conv2D(filters=3, kernel_size=5, padding='valid', strides=5)             # p = 0
conv2 = Conv2D(filters=3, kernel_size=5, padding='same', strides=5)

print(f"x2 (valid padding) : {conv1(images).shape}\n") #{conv1(images).numpy()}\n
print(f"x2 (same padding) : {conv2(images).shape}\n")  #{conv2(images).numpy()}\n


x (valid padding) : (1, 24, 24, 3)

x (same padding) : (1, 28, 28, 3)

x2 (valid padding) : (1, 5, 5, 3)

x2 (same padding) : (1, 6, 6, 3)

